server.port: 9094

spring:
  cloud:
    gateway:
      routes:
      - id: workspaces
        uri: localhost:9090
      predicates:
        - Path = workspaces-service/
      - id: employees
        uri: employees-service/employees
